SingleViewApi.Tests/V1/UseCase/GetCombinedSearchResultsByNameUseCaseTests.cs
SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs

https://trello.com/c/f43c8CNR/179-sort-results-by-relevance-independent-of-system
Search results have subsequent data sources results appended to rather than collated with the initial result set.
Added `DataSource` to the `SortByRelevance` method and tested for collation of data sources in search results.

Collate Data Sources in Search Results

---

SingleViewApi.Tests/V1/Gateways/AcademyGatewayTests.cs
SingleViewApi.Tests/V1/UseCase/GetCombinedSearchResultsByNameUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/GetHousingBenefitsAccountsByCustomerNameUseCaseTests.cs
SingleViewApi/Startup.cs
SingleViewApi/V1/Boundary/Response/HousingBenefitsSearchResponseObject.cs
SingleViewApi/V1/Controllers/CombinedSearchController.cs
SingleViewApi/V1/Gateways/AcademyGateway.cs
SingleViewApi/V1/Gateways/Interfaces/IAcademyGateway.cs
SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs
SingleViewApi/V1/UseCase/GetHousingBenefitsAccountsByCustomerNameUseCase.cs
SingleViewApi/V1/UseCase/Interfaces/IGetHousingBenefitsAccountsByCustomerNameUseCase.cs

https://trello.com/c/sz12rSq0/194-sv-connect-to-academy-housing-benefits-search-endpoint
We need to combine search results from [Academy API](https://github.com/LBHackney-IT/academy-api)'s `/api/v1/benefits/search` endpoint into Single View API's search.
Refactored Academy gateway to include the Housing Benefits search endpoint, added new use case to get Housing Benefits accounts and included this in the combined search use case.
None.

Add Academy Housing Benefits to Search

---

SingleViewApi.Tests/V1/UseCase/GetJigsawCustomerByIdUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/GetPersonApiByIdUseCaseTests.cs
SingleViewApi/V1/Boundary/KnownAddress.cs
SingleViewApi/V1/UseCase/GetJigsawCustomerByIdUseCase.cs
SingleViewApi/V1/UseCase/GetPersonAPIByIdUseCase.cs

[Trello Card](https://trello.com/c/5Z5kwbMk/221-display-where-addresses-are-coming-from)
as a user I would like to see where addresses are coming from,
so that I could correct information at the source where appropriate
Currently the API doesn't return the data source of each address, so we cannot yet update the frontend to display that data on the frontend to be viewed by users.
Added `DataSourceName` as a mandatory attribute to the `SingleViewApi.V1.Boundary.KnownAddress` class
Updated all relevant UseCases to include the new attribute
Renamed `customer` to `JigsawResponse` in `GetJigsawCustomerByIdUseCase.cs` for clarity
- [ x ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ x ] Added tests to cover all new …

New DataSourceName attr on KnownAddress + Tests

---

SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs
SingleViewApi/V1/Boundary/Response/MergedCustomerResponseObject.cs
SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs

https://trello.com/c/ebVVwsas/232-update-mergedcustomer-to-display-cautionary-alerts
- Show cautionary alerts on a merged customer. 
- Update `MergedCustomerResponseObject` to show cautionary alerts (if any).

Update MergedCustomer To Display Cautionary Alerts

---

SingleViewApi.Tests/V1/Controllers/CombinedSearchControllerTests.cs
SingleViewApi.Tests/V1/Gateways/CustomerGatewayTests.cs
SingleViewApi.Tests/V1/UseCase/GetCombinedSearchResultsByNameUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/GetCouncilTaxAccountsByCustomerNameUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/GetHousingBenefitsAccountsByCustomerNameUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/GetJigsawCustomersUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/GetSearchResultsByNameUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/SearchSingleViewUseCaseTests.cs
SingleViewApi/V1/Boundary/Response/SearchResponseObject.cs
SingleViewApi/V1/Controllers/CombinedSearchController.cs
SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs
SingleViewApi/V1/UseCase/GetCouncilTaxAccountsByCustomerNameUseCase.cs
SingleViewApi/V1/UseCase/GetHousingBenefitsAccountsByCustomerNameUseCase.cs
SingleViewApi/V1/UseCase/GetJigsawCustomersUseCase.cs
SingleViewApi/V1/UseCase/GetSearchResultsByNameUseCase.cs
SingleViewApi/V1/UseCase/Interfaces/IGetCombinedSearchResultsByNameUseCase.cs
SingleViewApi/V1/UseCase/SearchSingleViewUseCase.cs

GET `/api/v1/search?firstName={firstName}&lastName={lastName}&dateOfBirth={dd/mm/yyyy}`
Returns a search response containing an array of matching 'groupedResults' matching the name query and another array of 'ungroupedResults'.
`{
"searchResponse": {
"groupedResults": [
{
"id": "044be9c3-5c2f-42d6-beb0-05cd18271bbc",
"dataSource": "single-view",
"firstName": "Test",
"surName": "User",
"title": null,
"middleName": null,
"preferredFirstName": null,
"preferredSurname": null,
"dateOfBirth": "1980-02-01T00:00:00",
"niNumber": null,
"personTypes": null,
"isPersonCautionaryAlert": false,
"isTenureCautionaryAlert": false,
"knownAddresses": null
},
{
"id": "37b39dbb-a657-48cc-9dc7-598e8b682d98",
"dataSource": "single-view",
"firstName": "Test",
"surName": "User",
"title": null,
"middleName": null, …

Refactor of API To Display Grouped Search Results - BREAKING CHANGE, DO NOT DEPLOY UNTIL FRONT END IS READY

---

SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs
SingleViewApi.Tests/V1/UseCase/GetJigsawCustomerByIdUseCaseTests.cs
SingleViewApi/V1/Boundary/Response/CustomerResponseObject.cs
SingleViewApi/V1/Boundary/Response/Jigsaw/JigaswCustomerResponseObject.cs
SingleViewApi/V1/Boundary/Response/MergedCustomerResponseObject.cs
SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs
SingleViewApi/V1/UseCase/GetJigsawCustomerByIdUseCase.cs

https://trello.com/c/X96j0Fwt/239-display-missing-info-from-jigsaw
- Include following missing info on API so that it can be retrieved on front end to view.
- pregnancy Due Date
- accommodation Type 
- housing Circumstances
- is Settled
- support Worker - 
- gender
- Update GetJigsawCustomerByIUseCase to map the additional information from the Jigsaw data.

Display missing info from jigsaw

---

SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs
SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs

National insurance number was not visible on the merged records. (Returned as `null` in a response object)
- National insurance number has been mapped from `CustomerResponseObject` to `MergedCutomer`

Fix bug - NI Number not visible on merged records

---

SingleViewApi.Tests/V1/UseCase/GetJigsawCasesByCustomerIdUseCaseTests.cs
SingleViewApi/V1/UseCase/GetJigsawCasesByCustomerIdUseCase.cs

[Remove asterisks from additional factors questions](https://trello.com/c/i1cc8nXi/247-asterisks-in-additional-factors-answers-from-api)
Currently, Additional Factors questions and answers have leading asterisks.
Introduced a method to remove the asterisks and leading and trailing whitespace.

Remove asterisks from additional factors questions

---

SingleViewApi.Tests/V1/Gateways/JigsawGatewayTests.cs
SingleViewApi/V1/Gateways/JigsawGateway.cs

https://trello.com/c/9raxwnpi/266-jigsaw-case-information-failing-to-load
Additional factors and Health and wellbeing data for Jigsaw customers were not loading. Console threw a JSON parsing error.
Replaced a base url to point at the write direction to fetch data from Jigsaw.

Replace base url for additional-factors and health-and-well-being data

---

SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs

https://trello.com/c/IcZw3cge/286-group-search-results-regardless-if-middle-name-is-present-or-not

matching for grouping results fix

---

SingleViewApi/V1/Gateways/CustomerGateway.cs

Before this, some merges were failing when one of the dates of birth was in a non-UTC format.
Made a single change to convert the datetime passed to the SavedCustomer Add method to UTC.

Converts all dates of birth to UTC time to avoid database errors

---

terraform/staging/main.tf

This is to avoid CircleCI versioning issues in the terraform apply step

Try updating terraform db engine to 12.11 to match AWS desired version.

---

terraform/development/main.tf

The previous version of redis is being deprecated.

Update redis version to 7

---

SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs

Given that Single View fails to get results for a particular system, continue to return the results in list view.
Added try-catch for all the system data fetch steps.
Something to add in the near future is an indication that results failed to load from particular systems to be handled by the client / frontend

Gracefully get search results

---

terraform/development/main.tf

Current version is failing on AWS
Reduce cache size too - seems excessively provisioned

Bump redis to v7

---

SingleViewApi/Startup.cs

Was failing due to `System.InvalidCastException: Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported`
The addition of `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);` fixed this

Fix merged record creation

---

terraform/development/main.tf
terraform/production/main.tf
terraform/staging/main.tf

Update terraform to fix deployments
Staging and prod should use Postgres 12.14 which is what's currently on AWS (seems to have been an auto-update)
Elasticache should be redis v7 because v3 is not supported, and size should be t4g micro because large was overprovisioned.
Provider version should be in required providers block to fix the warning related to that

Terraform upgrade

---

terraform/development/main.tf
terraform/production/main.tf
terraform/staging/main.tf

Terraform is re-creating 7.0.7 when version is specified as 7.0 - should not do this so fixing the version at 7.0.7

Version should be explicitly 7.0.7

---

.circleci/config.yml

- Added Terraform development & staging & production state preview to the CCI feature branch workflow.
- Added a Safeguard to prevent development & staging & production terraform from applying automatically.
- Added additional Terraform state previews for the `development` and `master` branch workflows.
- Add the feature branch workflow.
- Removed unneeded `check-env` step.
- Made  `development` and `staging/master` workflow steps trigger on the corresponding _( `development` and `master`)_ branches.
- We want to know the impact of our Terraform file changes before we merge those changes to the main branch.
- We don't want to staging terraform to apply automatically because occasionally resource's state gets tweaked through the AWS Web UI console, which causes Terraform drift. If left …

Terraform friendly pipeline

---

terraform/development/main.tf

- This change **will trigger the SSL CA Certificate update** from `rds-ca-2019` to `rds-ca-rsa2048-g1`.
- The engine version for the redis cluster has also been updated to match what is on the AWS account.
- To resolve the drift between terraform and the resources on the AWS account.
- Also to trigger the SSL Certificate update done on the **aws-hackney-common-terraform** PR [#68](https://github.com/LBHackney-IT/aws-hackney-common-terraform/pull/68).

Resolve `development` terraform drift & upgrade SSL certificate

---

.circleci/config.yml

- Bump the pipeline's Node.js version from v16 to v20.
- The v16 is no longer supported.
- Node is needed for the SLS deploy.
- We need at least the `development` or `staging` deployments to be successful to apply the Terraform up to the `production` environment.
| Node too old error |
| --- |
| ![image](https://github.com/user-attachments/assets/1beb551d-d439-4641-a9b8-c51cec0b59ad) |

Upgrade the pipeline's Node.js from v16 to v20.

---

.circleci/config.yml

- Capped the serverless package used for API deployment to v3.
- The current version _(v4)_ requires a paid license to use _(read more [here](https://github.com/LBHackney-IT/housing-finance-interim-api/pull/140))_.

Cap serverless to v3 for licensing reasons.

---

terraform/staging/main.tf

- This change **will trigger the SSL CA Certificate update** from `rds-ca-2019` to `rds-ca-rsa2048-g1`.
- The engine version for the redis cluster has also been updated to match what is on the AWS account.
- To resolve the drift between terraform and the resources on the AWS account.
- Also to trigger the SSL Certificate update done on the **aws-hackney-common-terraform** PR [#68](https://github.com/LBHackney-IT/aws-hackney-common-terraform/pull/68).
| Terraform plan preview for the development environment |
| --- |
| ![image](https://github.com/user-attachments/assets/229416f7-6a3e-40af-80fe-55a79c05a641) |

Fix `staging` environment TF drift & trigger scheduled postgres SSL certificate upgrade.

---

terraform/production/main.tf

- This change **will trigger the SSL CA Certificate update** from `rds-ca-2019` to `rds-ca-rsa2048-g1`.
- The engine version for the redis cluster has also been updated to match what is on the AWS account.
- To resolve the drift between terraform and the resources on the AWS account.
- Also to trigger the SSL Certificate update done on the **aws-hackney-common-terraform** PR [#68](https://github.com/LBHackney-IT/aws-hackney-common-terraform/pull/68).
- This change also **triggers the downscale of the redis cache**, which was introduced by #115. This downscale was done because that functionality 'is broken at the current time', and even if it wasn't broken it only has ~20 records _(meaning redis is overscaled)_.
| Terraform plan preview for the production environment |
| --- |
| …

Fix `production` environment TF drift & which will trigger the scheduled postgres SSL certificate upgrade.

---

terraform/development/main.tf

This PR upgrades the postgres version from 12.17 to 16.1 through terraform. It also attaches the new `postgres16` parameter group to the database with the correct parameter values.
Part of the ongoing work of upgrading the postgres database versions so to avoid the AWS extended support costs.

Upgrade postgres version to 16.1

---

terraform/staging/main.tf

This PR upgrades the postgres version from 12.17 to 16.1 for the staging database. It also attaches the new postgres16 parameter group to the database with the correct parameter values.
Part of the ongoing work of upgrading the postgres database versions so to avoid the AWS extended support costs.

Staging: Update postgres version to 16.1

---

terraform/production/main.tf

This PR upgrades the postgres version from 12.17 to 16.1 through terraform. It also attaches the new `postgres16` parameter group to the database with the correct parameter values.
Part of the ongoing work of upgrading the postgres database versions so to avoid the AWS extended support costs.

Production: Update postgres version to 16.1

---

terraform/production/main.tf

- Merge the PR #130 from `master` into `development`
- Accidentally skipped the `development` branch.
- Need the `development` branch for deployment to the `development` environment.

Apply postgres database upgrade to v16 on `development` environment.

---

terraform/development/main.tf
terraform/staging/main.tf

- Fix the `development` single-view database's engine minor version drift.
- Fix the `staging` single-view database's engine minor version drift.
- Minor versions auto-upgrade, so the drift is inevitable.
- The `development` and `staging` drift blocks the release of the `production` drift fix.
- There's pending `production` drift from the PR #132 that didn't get applied due to the pipeline failure caused by the drift this PR aims to solve.

Fix `Corporate-Development` and `Corporate-Staging` Terraform drift.

---

.circleci/config.yml
SingleViewApi/build.cmd
SingleViewApi/build.sh
SingleViewApi/serverless.yml

This PR bumps Serverless Framework to version 4 and introduces a CircleCI context for the newly required license key.
It also removes the .NET version from the build artifact path, to remove one step when we upgrade it.

Upgrade CI deployment to Serverless Framework v4

---

.circleci/config.yml
SingleViewApi/package-lock.json
SingleViewApi/package.json

This change resolves a build failure because Serverless Framework 4 doesn't pick up globally installed modules. I'm not sure why this has changed (or how/if it's actually changed), but it's sensible to version the dependencies and installing the plugin using 'npm install' following the docs _also_ allows the command to succeed.
An example of a failing deploy is
https://app.circleci.com/pipelines/github/LBHackney-IT/single-view-api/932/workflows/47c8895f-8506-4f12-ae69-7fc3208a9ba0/jobs/5388:
```
✖ ServerlessError2: Serverless plugin "serverless-plugin-aws-alerts" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Use the --debug flag to learn more.
at PluginManager.resolveServicePlugins …
```

Define Serverless dependency versions
