SingleViewApi.Tests/V1/Gateways/ContactDetailsGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs, SingleViewApi/SingleViewApi.csproj, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/Response/CustomerResponseObject.cs, SingleViewApi/V1/Gateways/ContactDetailsGateway.cs, SingleViewApi/V1/Gateways/IContactDetailsGateway.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs, SingleViewApi/serverless.yml, docker-compose.yml, sample.env
add contact information to be returned from when returning customer details, example response: 
```json
{
"customer": {
"title": "Dr",
"preferredTitle": "Dr",
"preferredFirstName": "string",
"preferredMiddleName": "string",
"preferredSurname": "string",
"firstName": "string",
"middleName": "string",
"surname": "string",
"placeOfBirth": "string",
"dateOfBirth": "2022-04-28T13:59:23.604Z",
"knownAddresses": [
{
"fullAddress": "string",
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"currentAddress": true,
"startDate": "string",
"endDate": "string"
}
],
"dateOfDeath": "2022-04-28T13:59:23.604Z",
"isAMinor": true,
"contactDetails": {
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"targetId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"targetType": "person",
"contactInformation": {
"contactType": …
```
=> add contact details to customer response

.circleci/config.yml, SingleViewApi.Tests/Dockerfile, SingleViewApi.Tests/SingleViewApi.Tests.csproj, SingleViewApi.Tests/V1/Gateways/ExampleGatewayTests.cs, SingleViewApi.Tests/V1/Infrastructure/ExampleContextTests.cs, SingleViewApi/Dockerfile, SingleViewApi/SingleViewApi.csproj, SingleViewApi/Startup.cs, SingleViewApi/build.sh, SingleViewApi/serverless.yml, terraform/development/main.tf
Happy days, we're in dot net6 and working on development 
https://gu90i35pz2.execute-api.eu-west-2.amazonaws.com/development/swagger/index.html
=> Upgrade to dot net6

.circleci/config.yml
Enable migrations on staging and production
=> Enable migrations 

SingleViewApi.Tests/V1/Controllers/CustomerControllerTests.cs, SingleViewApi.Tests/V1/Gateways/CustomerDataSourceGatewayTests.cs, SingleViewApi.Tests/V1/Gateways/CustomerGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/CreateCustomerUseCaseTests.cs, SingleViewApi/SingleViewApi.csproj, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/Request/CreateCustomerRequest.cs, SingleViewApi/V1/Controllers/CustomerController.cs, SingleViewApi/V1/Domain/SavedCustomer.cs, SingleViewApi/V1/Factories/CustomerFactory.cs, SingleViewApi/V1/Gateways/CustomerDataSourceGateway.cs, SingleViewApi/V1/Gateways/CustomerGateway.cs, SingleViewApi/V1/Gateways/ICustomerDataSourceGateway.cs, SingleViewApi/V1/Gateways/ICustomerGateway.cs, SingleViewApi/V1/UseCase/CreateCustomerUseCase.cs, SingleViewApi/V1/UseCase/Interfaces/ICreateCustomerUseCase.cs
refactored how what params gateways need
=> save customer usecase and enpoint

SingleViewApi.Tests/V1/Gateways/CustomerGatewayTests.cs, SingleViewApi/V1/Infrastructure/SingleViewContext.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> Find saved customer

SingleViewApi.Tests/V1/Controllers/CustomerControllerTests.cs, SingleViewApi.Tests/V1/UseCase/GetPersonApiByIdUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/Controllers/CustomerController.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs, SingleViewApi/V1/UseCase/GetPersonAPIByIdUseCase.cs, SingleViewApi/V1/UseCase/Interfaces/IGetCustomerByIdUseCase.cs, SingleViewApi/V1/UseCase/Interfaces/IGetPersonApiByIdUseCase.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> Get customer

SingleViewApi.Tests/V1/Gateways/EqualityInformationGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetPersonApiByIdUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/Response/CustomerResponseObject.cs, SingleViewApi/V1/Boundary/Response/EqualityInformationResponseObject.cs, SingleViewApi/V1/Gateways/EqualityInformationGateway.cs, SingleViewApi/V1/Gateways/IEqualityInformationGateway.cs, SingleViewApi/V1/Gateways/IVulnerabilityGateway.cs, SingleViewApi/V1/Gateways/VulnerabilityGateway.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs, SingleViewApi/V1/UseCase/GetPersonAPIByIdUseCase.cs, SingleViewApi/serverless.yml, sample.env
Merge into development to test
=> Equality API integration

CODEOWNERS, Makefile, SingleViewApi.Tests/V1/Gateways/AcademyGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetAllNotesUseCaseTests.cs, SingleViewApi.Tests/V1/UseCase/GetCouncilTaxNotesUseCaseTests.cs, SingleViewApi.Tests/V1/UseCase/GetHousingBenefitsNotesUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/Response/AcademyNotesResponseObject.cs, SingleViewApi/V1/Extensions.cs, SingleViewApi/V1/Gateways/AcademyGateway.cs, SingleViewApi/V1/Gateways/Interfaces/IAcademyGateway.cs, SingleViewApi/V1/UseCase/GetAllNotesUseCase.cs, SingleViewApi/V1/UseCase/GetCouncilTaxNotesUseCase.cs, SingleViewApi/V1/UseCase/GetHousingBenefitsNotesUseCase.cs, SingleViewApi/V1/UseCase/Interfaces/IGetCouncilTaxNotesUseCase.cs, SingleViewApi/V1/UseCase/Interfaces/IGetHousingBenefitsNotesUseCase.cs
Implement housing benefits and council tax notes
=> Academy notes

SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs, SingleViewApi/V1/Boundary/Response/MergedCustomerResponseObject.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs
GET `/customers/:id`
```json
{
"customer": {
"id": "string",
"title": "string",
"preferredTitle": "Dr",
"preferredFirstName": "string",
"preferredMiddleName": "string",
"preferredSurname": "string",
"firstName": "string",
"surname": "string",
"placeOfBirth": "string",
"knownAddresses": [
{
"fullAddress": "string",
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"currentAddress": true,
"startDate": "string",
"endDate": "string",
"dataSourceName": "string"
}
],
"allContactDetails": [
{
"dataSourceName": "string",
"isActive": true,
"sourceServiceArea": "string",
"contactType": "string",
"subType": "string",
"value": "string",
"description": "string",
"addressExtended": {
"uprn": "string",
"isOverseasAddress": true,
"overseasAddress": "string"
}
}
],
"personTypes": [
"string"
], …
```
=> refactor what data contact details return

SingleViewApi.Tests/V1/Gateways/JigsawGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetJigsawCasesByCustomerIdUseCaseTests.cs, SingleViewApi/V1/Boundary/Response/CasesResponseObject.cs, SingleViewApi/V1/Boundary/Response/Jigsaw/JigsawCaseAdditionalFactorsResponseObject.cs, SingleViewApi/V1/Gateways/Interfaces/IJigsawGateway.cs, SingleViewApi/V1/Gateways/JigsawGateway.cs, SingleViewApi/V1/UseCase/GetJigsawCasesByCustomerIdUseCase.cs
GET `/api/v1/getJigsawCases`
```json
{
"currentCase": {
"id": 0,
"statusName": "string",
"dateOfApproach": "2022-07-26T15:30:47.096Z",
"isCurrent": true,
"assignedTo": "string",
"isV2LegacyCase": true
},
"additionalFactors": [
{
"legend": "string",
"info": [
{
"question": "string",
"answer": "string"
}
]
}
],
"healthAndWellBeing": [
{
"legend": "string",
"info": [
{
"question": "string",
"answer": "string"
}
]
}
],
"placementInformation": [
{
"placementType": "string",
"fullAddressDetails": {
"id": 0,
"houseName": "string",
"houseNumber": "string",
"street": "string",
"town": "string",
"county": "string",
"postcode": "string",
"apartment": "string",
"roomNumber": "string",
"locality": "string",
"latitude": "string",
"longitude": "string",
"freetext": "string"
},
"placementDuty": "string", …
```
=> return jigsaw case info data

SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs, SingleViewApi.Tests/V1/UseCase/GetJigsawCustomerByIdUseCaseTests.cs, SingleViewApi.Tests/V1/UseCase/GetPersonApiByIdUseCaseTests.cs, SingleViewApi/V1/Boundary/Response/CustomerResponseObject.cs, SingleViewApi/V1/Boundary/Response/Jigsaw/JigaswCustomerResponseObject.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs, SingleViewApi/V1/UseCase/GetJigsawCustomerByIdUseCase.cs, SingleViewApi/V1/UseCase/GetPersonAPIByIdUseCase.cs
return contact details from jigsaw and refactor person api contacts
=> Jigsaw contact details

SingleViewApi/V1/Controllers/PostgresController.cs, SingleViewApi/V1/Extensions.cs, SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs, SingleViewApi/V1/UseCase/GetCouncilTaxAccountByAccountRefUseCase.cs, SingleViewApi/V1/UseCase/GetCouncilTaxAccountsByCustomerNameUseCase.cs, SingleViewApi/V1/UseCase/GetHousingBenefitsAccountByAccountRefUseCase.cs, SingleViewApi/V1/UseCase/GetHousingBenefitsAccountsByCustomerNameUseCase.cs, SingleViewApi/V1/UseCase/GetJigsawCustomerByIdUseCase.cs, SingleViewApi/V1/UseCase/GetJigsawCustomersUseCase.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> upcase results from jigsaw and academy

SingleViewApi.Tests/SingleViewApi.Tests.csproj, SingleViewApi.Tests/V1/Gateways/EqualityInformationGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs, SingleViewApi.Tests/V1/UseCase/GetPersonApiByIdUseCaseTests.cs, SingleViewApi/SingleViewApi.csproj, SingleViewApi/V1/Boundary/Response/EqualityInformationResponseObject.cs, SingleViewApi/V1/Boundary/Response/MergedCustomerResponseObject.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs, SingleViewApi/V1/UseCase/GetPersonAPIByIdUseCase.cs
- Restore equality information
=> Restore equality information

SingleViewApi.Tests/V1/Gateways/JigsawGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetJigsawCasesByCustomerIdUseCaseTests.cs, SingleViewApi/V1/Gateways/JigsawGateway.cs, SingleViewApi/V1/UseCase/GetJigsawCasesByCustomerIdUseCase.cs
- Fix issue where no current case exists
=> Fix exception when there is no current case

SingleViewApi/V1/UseCase/GetJigsawCasesByCustomerIdUseCase.cs
- Adds null check when removing asterix on Jigsaw case info
=> null check on remove asterix

SingleViewApi/V1/UseCase/GetPersonAPIByIdUseCase.cs
https://trello.com/c/7XzCZHij/270-some-personapi-records-are-failing-to-load
=> added null check to person title

SingleViewApi.Tests/V1/UseCase/GetJigsawNotesUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/Response/Jigsaw/JigsawNotesResponseObject.cs, SingleViewApi/V1/Boundary/Response/NoteResponseObject.cs, SingleViewApi/V1/Gateways/AcademyGateway.cs, SingleViewApi/V1/Gateways/Interfaces/IJigsawGateway.cs, SingleViewApi/V1/Gateways/JigsawGateway.cs, SingleViewApi/V1/UseCase/GetJigsawActiveCaseNotesUseCase.cs, SingleViewApi/V1/UseCase/GetJigsawNotesUseCase.cs, SingleViewApi/V1/UseCase/Interfaces/IGetJigsawActiveCaseNotesUseCase.cs
https://trello.com/c/2ochi746/297-notes-on-jigsaw-not-showing-up-on-single-view
Updates the Jigsaw Notes Use Case to also get notes for the active customer case.
=> Add new Use Case To Fetch Active Case Jigsaw Notes

SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs
Currently the NI number is not being mapped from equality information data.
National Insurance number is being mapped from equality information to merged customer.
=> Add National Insurance number from equality information to merged customer

SingleViewApi/V1/UseCase/CreateCustomerUseCase.cs
https://trello.com/c/9lBpGPAE/284-housing-benefits-are-not-showing-up-when-merging-records
System names are not matching as their casings differ. 
Implemented a method to ignore cases of system names.
=> Ignore cases while comparing data-source names

Makefile, SingleViewApi.Tests/V1/UseCase/GetPersonApiByIdUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/KnownAddress.cs, SingleViewApi/V1/Gateways/Interfaces/ITenureGateway.cs, SingleViewApi/V1/Gateways/TenureGateway.cs, SingleViewApi/V1/UseCase/GetPersonAPIByIdUseCase.cs, SingleViewApi/serverless.yml, docker-compose.yml, sample.env
New env param introduced `TENURE_API`, all set on AWS already. 
also person API customers and merged customers will now return extended known addresses
```json
...
"knownAddresses": [
{
"fullAddress": "26 Broadway House  Jackman Street, E8 4QY",
"id": "73e347f6-7a4e-2584-3f69-58974a2726b5",
"currentAddress": true,
"startDate": "2016-11-28",
"endDate": null,
"householdMembers": [
{
"id": "55d0d467-a325-28e8-c8c3-cff90bdaf19c",
"type": 0,
"fullName": "FAKE_Katie FAKE_Lewis",
"isResponsible": true,
"dateOfBirth": "1956-10-09T00:00:00Z",
"personTenureType": 0
},
{
"id": "5f33311b-9c4c-1de4-839b-a503871dba39",
"type": 0,
"fullName": "FAKE_Marilyn FAKE_Barber",
"isResponsible": false,
"dateOfBirth": "1987-10-28T00:00:00Z",
"personTenureType": 3
},
{
"id": "ee5914b7-1b3e-972a-e69b-d23ec5cffb1a", …
```
=> add tenture api so that household members could be displayed

SingleViewApi/V1/Boundary/HousingBenefitsAccountInfo.cs, SingleViewApi/V1/Boundary/Response/CustomerResponseObject.cs, SingleViewApi/V1/Boundary/Response/HousingBenefitsRecordResponseObject.cs, SingleViewApi/V1/UseCase/GetHousingBenefitsAccountByAccountRefUseCase.cs
https://trello.com/c/1OhKbSFK/322-field-resident-housing-benefit-entitlement
- added hb weekly entitlement to customer response object
=> added hb weekly amount to response object

SingleViewApi/V1/Boundary/HousingBenefitsAccountInfo.cs, SingleViewApi/V1/Boundary/Response/HousingBenefitsRecordResponseObject.cs, SingleViewApi/V1/UseCase/GetHousingBenefitsAccountByAccountRefUseCase.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
=> update to wkbd object

SingleViewApi/V1/Boundary/HousingBenefitsAccountInfo.cs, SingleViewApi/V1/Boundary/Response/HousingBenefitsRecordResponseObject.cs, SingleViewApi/V1/UseCase/GetHousingBenefitsAccountByAccountRefUseCase.cs
=> added landlord details to hb response

SingleViewApi/V1/Boundary/HousingBenefitsAccountInfo.cs, SingleViewApi/V1/Boundary/Response/HousingBenefitsRecordResponseObject.cs, SingleViewApi/V1/UseCase/GetHousingBenefitsAccountByAccountRefUseCase.cs
Map fields from Academy API 
https://trello.com/c/eXvtVZTf/295-extra-field-last-payment-made-by-extracting-information-from-rent-transactions
=> added last payment details to response object

SingleViewApi.Tests/V1/Gateways/SharedPlanGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/Request/GetSharedPlanRequest.cs, SingleViewApi/V1/Boundary/Response/MergedCustomerResponseObject.cs, SingleViewApi/V1/Boundary/Response/SharedPlanResponseObject.cs, SingleViewApi/V1/Gateways/Interfaces/ISharedPlanGateway.cs, SingleViewApi/V1/Gateways/SharedPlanGateway.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs, SingleViewApi/serverless.yml, sample.env
https://trello.com/c/nlLoZGVi/22-integrate-shared-plan-with-single-view
Fetch shared plan ids for a particular resident
- Created new gateway to retrieve shared plan ids
- Updated customer response object to include shared plan ids
=> Get shared plan ids 

SingleViewApi.Tests/V1/Gateways/SharedPlanGatewayTests.cs, SingleViewApi.Tests/V1/UseCase/GetCustomerByIdUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/Boundary/Request/GetSharedPlanRequest.cs, SingleViewApi/V1/Boundary/Response/MergedCustomerResponseObject.cs, SingleViewApi/V1/Boundary/Response/SharedPlanResponseObject.cs, SingleViewApi/V1/Gateways/Interfaces/ISharedPlanGateway.cs, SingleViewApi/V1/Gateways/SharedPlanGateway.cs, SingleViewApi/V1/UseCase/GetCustomerByIdUseCase.cs, SingleViewApi/serverless.yml, docker-compose.yml, sample.env
=> Updating branch with master

terraform/staging/main.tf
Trying to fix the terraform that is auto-updating the DB and causing the "apply" step to fail.
=> Prevent auto minor version upgrade to fix CircleCI deployment

SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs
Reverts LBHackney-IT/single-view-api#106
=> Revert "Gracefully get search results"

.circleci/config.yml
To fix pipeline issue
"Package dotnet-ef 8.0.1 is not compatible with net6.0"
=> Set dotnet ef version to 6.*

SingleViewApi.Tests/V1/UseCase/GetCombinedSearchResultsByNameUseCaseTests.cs, SingleViewApi/Startup.cs, SingleViewApi/V1/UseCase/GetCombinedSearchResultsByNameUseCase.cs, SingleViewApi/V1/UseCase/SearchSingleViewUseCase.cs, database/Makefile, docker-compose.yml
Added some log calls to the get combined search results UseCase to allow for easier debugging of issues that arise
=> Better logging for search results

terraform/development/main.tf, terraform/production/main.tf, terraform/staging/main.tf
Fix terraform init for this version
=> Engine 7.x for ES

terraform/development/main.tf, terraform/production/main.tf, terraform/staging/main.tf
Doesn't accept version 7.x - try version 7.0 again
=> Version reset

terraform/development/main.tf, terraform/production/main.tf, terraform/staging/main.tf
Merge PRs to master:
-  #127 
-  #128 
The staging upgrade only applies on the master branch
- Upgrade postgres version for development & staging to 16.1
=> Merge #127 & #128 to master
